
name: msunityapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Adjusted to match Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  mime: ^1.0.4
  intl: ^0.17.0
  image_picker: ^1.0.7
  http: ^0.13.6
  flutter_image_compress: ^1.1.3
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/login.jpeg
    # - assets/default_event_image.png # Uncommented this line to include the default event image

  uses-material-design: true